[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cryosiam"
version = "1.0"
description = "CryoSiam: Deep Learning-based Cryo-ET Analysis"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "Frosina Stojanovska", email = "stojanovska.frose@gmail.com" }
]
dependencies = [
  "edt",
  "python-elf",
  "h5py",
  "itk",
  "lightning",
  "monai",
  "mrcfile",
  "numpy",
  "pandas",
  "scipy",
  "plotly",
  "PyYAML",
  "scikit_learn",
  "scikit-image",
  "starfile",
  "torch",
  "torchvision",
  "umap-learn"
]

[project.scripts]
cryosiam = "cryosiam.cli:main"
